services:
  - type: web
    name: dopl-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false